#Aquí vamos a preparar la configuración de Spring.
server:
  port: 8081

spring:
    datasource:
        url: jdbc:h2:mem:hotel
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: update
    h2:
        console:
            enabled: true
